version: "3.8"

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432

  backend:
    build:
      context: ./backend
    command: python -m uvicorn main:app --host 0.0.0.0
    ports:
      - 8008:8000
    env_file:
      - .env
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    command: serve -s dist -l 5000
    ports:
      - 8009:5000
    env_file:
      - .env
    depends_on:
      - backend