name: backend_testing
on: push
jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-20.04
    steps:
      - cd backend
      - python -m pip install poetry
      - poetry install
      - poetry run pytest
