name: backend_testing

on:
  pull_request:
    types: [opened, review_requested]
  push:
    branches:
      - 'main'

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: python -m pip install poetry
      - run: poetry install
      - run: pip install .
      - run: poetry run pytest
