name: backend_testing

on: [push]

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-20.04
    defaults:
      run:
        ls -la
        # working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - run: python -m pip install poetry
      - run: poetry install
      - run: pip install .
      - run: poetry run pytest
